;;;; Capture what lem-relay/protobuf sends for a scripted session in the
;;;; real editor, as a golden fixture for the Rust half
;;;; (lem-protocol/tests/relay_v1_fixture.rs):
;;;;
;;;;   proto/fixtures/relay-session.v1.bin  every ToDisplay, length-delimited
;;;;   proto/fixtures/relay-session.v1.txt  the same in text format, to review
;;;;
;;;; Regenerate from the repository root after changing the relay, the
;;;; codec or the schema (`make toolchain` first; protoc must be on PATH):
;;;;
;;;;   PATH=$PWD/frontends/ratatui/toolchain/bin:$PATH \
;;;;   sbcl --non-interactive --load .qlot/setup.lisp \
;;;;        --load frontends/ratatui/scripts/capture-relay-v1.lisp

(defpackage :capture-relay-v1
  (:use :cl))
(in-package :capture-relay-v1)

(handler-bind ((warning #'muffle-warning))
  (asdf:load-system "lem-relay/protobuf")
  ;; For its links (ADR 0018); it brings Lem's extensions with it.
  (asdf:load-system "lem-ratatui"))

(defclass capture-relay (lem-relay/relay:relay lem:implementation) ()
  (:default-initargs
   :name :capture-relay-v1
   :redraw-after-modifying-floating-window t
   :no-force-needed nil
   :window-left-margin 1
   :window-bottom-margin 1))

(defparameter *fixtures*
  (asdf:system-relative-pathname "lem-relay" "../proto/fixtures/"))

(defun write-fixtures (bodies)
  "BODIES, serialised ToDisplay messages in order, as the binary fixture
and its text-format twin."
  (ensure-directories-exist *fixtures*)
  (with-open-file (out (merge-pathnames "relay-session.v1.bin" *fixtures*)
                       :direction :output :if-exists :supersede
                       :element-type '(unsigned-byte 8))
    (dolist (body bodies)
      (lem-relay/protobuf/framing:write-delimited out body)))
  (with-open-file (out (merge-pathnames "relay-session.v1.txt" *fixtures*)
                       :direction :output :if-exists :supersede
                       :external-format :utf-8)
    (format out "# Generated by scripts/capture-relay-v1.lisp; see relay-session.v1.bin.~%")
    (dolist (body bodies)
      (format out "~%# ToDisplay~%")
      (cl-protobufs:print-text-format
       (cl-protobufs:deserialize-from-bytes 'cl-protobufs.lem.relay.v1:to-display body)
       :stream out))))

(defun capture ()
  (let ((relay (make-instance 'capture-relay))
        (state (lem-relay/protobuf/codec:make-codec-state))
        (bodies '()))
    (setf (lem-relay/relay:relay-sink relay)
          (lambda (message)
            (let ((seq (lem-relay/protobuf/codec:next-seq state)))
              (push (lem-relay/protobuf/codec:encode message state seq) bodies)
              seq)))
    (lem:with-current-buffers ()
      (lem:with-implementation relay
        (lem:setup-first-frame)
        (flet ((redraw () (lem:redraw-display :force t))
               (type-text (string)
                 (lem:insert-string
                  (lem:buffer-point (lem:window-buffer (lem:current-window))) string)))
          (redraw)
          (type-text (format nil "(defun héllo () 'λ)~%;; 日本語 https://lem-project.github.io"))
          ;; The scan Lem runs on the edited lines, which puts the links.
          (let ((buffer (lem:window-buffer (lem:current-window))))
            (lem-ratatui/links:scan-links (lem:buffer-start-point buffer)
                                          (lem:buffer-end-point buffer)))
          (lem:redraw-display)
          (lem:split-window-vertically (lem:current-window))
          (redraw)
          (lem/common/timer:with-timer-manager
              (make-instance 'lem/common/timer:timer-manager)
            (lem:display-popup-message "a popup"))
          (redraw)
          (lem:set-background "#1c1c1c")
          (lem-if:update-cursor-shape relay :bar)
          (lem:redraw-display)
          (lem-if:clipboard-copy relay "copied"))))
    (write-fixtures (reverse bodies))
    (format t "~&Wrote ~D messages to ~A~%" (length bodies) *fixtures*)))

(capture)
